---
name: pubnub-react-chat-components
version: v0.3.0
scm: github.com/pubnub/react-chat-components
schema: 1
files:
  - dist/index.js
  - dist/index.es.js
changelog:
  - changes:
      - text: Remove default subscription to the 'user channel'
        type: feature
    date: 2021-08-09
    version: v0.3.0
  - changes:
      - text: Remove internal emoji picker component
        type: feature
      - text: Add 'refetch' option to usePresence hook
        type: feature
      - text: Remove default welcome messages on MessageList
        type: improvement
      - text: Improve the display of actions/reactions on certain themes
        type: improvement
    date: 2021-04-30
    version: v0.2.0
  - changes:
      - text: Initial public release
        type: feature
    date: 2021-04-09
    version: v0.1.0
