name: Automated product release

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]


jobs:
  check-release:
    name: Check release required
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && endsWith(github.repository, '-private') != true }}
    outputs:
      release: ${{ steps.check.outputs.ready }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - id: check
        name: Check pre-release completed
        uses: ./.github/.release/actions/actions/checks/release
        with:
          token: ${{ secrets.GH_TOKEN }}
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: check-release
    if: ${{ needs.check-release.outputs.release == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # This should be the same as the one specified for on.pull_request.branches
          ref: master
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Publish React to NPM
        uses: ./.github/.release/actions/actions/services/npm
        with:
          token: ${{ secrets.GH_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          package-path: packages/react/package.json
          actions: "build,publish"
          build-command: npm run build
          build-path: packages/react/dist
          artifacts-filter: true
      - name: Publish React Native to NPM
        uses: ./.github/.release/actions/actions/services/npm
        with:
          token: ${{ secrets.GH_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          package-path: packages/react-native/package.json
          actions: "build,publish"
          build-command: npm run build
          build-path: packages/react-native/dist
          artifacts-filter: true
      - name: Create Release
        uses: ./.github/.release/actions/actions/services/github-release
        with:
          token: ${{ secrets.GH_TOKEN }}
          last-service: true

