name: Test

on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REACT_APP_PUB_KEY: ${{ secrets.REACT_APP_PUB_KEY }}
  REACT_APP_SUB_KEY: ${{ secrets.REACT_APP_SUB_KEY }}
defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Run builtin test cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache React Chat Component dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-yarn-rcc-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-rcc-
          path: ${{ steps.yarn-cache-dir-path.outputs.YARN_CACHE_DIR }}
      - name: Run types validation
        run: |
          yarn install --prefer-offline --frozen-lockfile
          yarn run test
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: pubnub/chat-components-e2e-tests
          # This after Playwright setup will be completed, should be set back to master.
          ref: Playwright-setup-UI-1598
          token: ${{ secrets.GH_TOKEN }}
      - name: Install e2e framework dependencies
        run: |
          RCC_PATH=${{ github.workspace }}/react/testing_apps
          [[ -d "$RCC_PATH" ]] &&  rm -rf "$RCC_PATH"
          cd ${{ github.workspace }}/react
          npm ci
      - name: Cache Playwright browsers
        id: playwright-browsers-cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-playwright-${{ hashFiles('react/package-lock.json') }}
          restore-keys: ${{ runner.os }}-playwright-
          path: ~/.cache/ms-playwright
      - name: Install Playwright browsers
        if: steps.playwright-browsers-cache.outputs.cache-hit != 'true'
        run: npx playwright install
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: react/testing_apps/react-chat-components
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache React Chat Component dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-yarn-rcc-${{ hashFiles('react/testing_apps/react-chat-components/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-rcc-
          path: ${{ steps.yarn-cache-dir-path.outputs.YARN_CACHE_DIR }}
      - name: Install React Chat Component dependencies
        run: |
          cd ${{ github.workspace }}/react/testing_apps/react-chat-components
          yarn install --prefer-offline --frozen-lockfile
      - name: Test application setup and run
        run: |
          cd ${{ github.workspace }}/react/testing_apps/react-chat-components/samples/react/group-chat
          yarn run setup
          yarn run start &
      - name: Run e2e tests
        run: |
          cd ${{ github.workspace }}/react
          npx playwright test
      - name: Expose e2e test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ${{ github.workspace }}/react/playwright-report/*.html
          retention-days: 7
